README.md : HyperLinking the encore image.
encoredev/encore pull request #464
Opened 2022-10-22 10:04 UTC by Abubakrce19

I hyperlinked the encore image with its encore's official website, so a user can access website with single click,
Minor but impactful.
Thank you!

2022-10-22 18:07 UTC, Abubakrce19 commented
@eandre

2022-10-24 04:17 UTC, Abubakrce19 commented
@eandre

2022-10-24 15:42 UTC, DomBlack requested changes

2022-10-24 15:42 UTC, DomBlack commented on README.md
> +</a>
Do you mind fixing the spacing?

```suggestion
  <a href="https://encore.dev">
    <img width="1500px" src="https://encore.dev/assets//branding/github_header.png" alt="Encore - Backend development engine">
  </a>
```

2022-10-24 15:54 UTC, Abubakrce19 commented on README.md
> +</a>
> Do you mind fixing the spacing?
@DomBlack 
Done!!
Sorry for that!

2022-10-24 16:01 UTC, merged