Add improved secrets management
encoredev/encore pull request #548
Opened 2022-12-15 19:45 UTC by eandre

This adds much-improved secrets management to the Encore CLI.
New functionality includes being able to specify per-environment secrets,
listing the configured secrets and archiving secret values.

2022-12-19 10:41 UTC, DomBlack requested changes

2022-12-19 10:41 UTC, DomBlack commented on cli/cmd/encore/secrets/list.go
> +				checkNo  = "\u2717"
Might we have issues with some terminals with these unicode's?

The `errslist` has two different formatters (unicode and ascii) to try and combat this issue - but I guess we can leave it until we get confirmed errors from people

2022-12-19 10:41 UTC, DomBlack commented on cli/cmd/encore/secrets/secrets.go
> +	Use:   "secret",
```suggestion
	Use:   "secret",
	Aliases: []string { "secrets" },
```

2022-12-19 10:41 UTC, DomBlack commented on devbuild.sh
> +  "-X 'encr.dev/internal/conf.defaultPlatformURL=http://localhost:9000'"
These three only make sense if you are able to run our platform locally; I think for this script we should remove them...

2022-12-19 13:45 UTC, DomBlack approved these changes

2023-01-20 10:10 UTC, ekerfelt approved these changes

2023-01-20 10:11 UTC, merged